In [2]:
import numpy as np 
import os
import csv

arr = np.arange(15).reshape((3, 5))
print(arr)
np.random.shuffle(arr)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]


In [29]:
arr = np.array([[0, 1, 0],\
                [1, 0, 1],\
                [1, 1, 1],\
                [1, 0, 0]])
targets = np.array([1, 1, 0, 1, 0, 0])

In [30]:
tmp = arr[:, 1] == 1
print(np.sum(tmp))
print(targets[tmp])

2


IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 4

In [31]:
print(tmp)
print(arr[tmp])

[ True False  True False]
[[0 1 0]
 [1 1 1]]


In [32]:
max(set(targets), key=list(targets).count)

0

In [33]:
set(arr[:, 1])

{0, 1}

In [34]:
np.delete(arr, 1, 1)

array([[0, 0],
       [1, 1],
       [1, 1],
       [1, 0]])